### PR TITLE
Use updated naming to remove warning

### PR DESCRIPTION
**Pull request by eclipse0922**
diag_suppress is  deprecated from cuda

### CODE REVIEW

**Comment by eclipse0922** [comment]
Linter changed 59 filest but not 'global.h'.

**Comment by bottler** [comment]
> Linter changed 59 filest but not `global.h`.

Don't worry about it. I suspect it's a Python thing, maybe with import ordering?

**Comment by eclipse0922** [comment]
> > Linter changed 59 filest but not `global.h`.
> 
> Don't worry about it. I suspect it's a Python thing, maybe with import ordering?

Then, do I need to do something more?

**Comment by bottler** [comment]
Thanks for asking. No need to do anything more. It needs to be dealt with by us internally.

**Comment by bottler** [comment]
Thanks for fixing this!

**Pull request closed without merging**
