### PR TITLE
Add nvidia channel for cudatoolkit

### PR DESCRIPTION
**Pull request by kampelmuehler**
nvidia channel is required for installing cudatoolkit

### CODE REVIEW

**Comment by kampelmuehler** [comment]
True, it was the combination `cudatoolkit -c nvidia` meanwhile, but it seems they changed it once more recently.

In any case with the current configuration it doesn't work (cant find `cudatoolkit`, since it got removed from the `pytorch` channel).
I'm currently trying to get `pytorch3d` running with what is suggested on the pytorch getting started page for linux and conda namely `conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`, but can't get it running thus far.

**Comment by bottler** [comment]
I'm afraid that's because we don't have conda packages for PyTorch 1.13.1 yet it came out on Friday while we had already started the release process for PyTorch3D 0.7.2. 

Can you try forcing pytorch 1.13.0?
```
conda install pytorch=1.13.0 torchvision pytorch-cuda=11.6 -c pytorch -c nvidia
conda install -c fvcore -c iopath -c conda-forge iopath fvcore
conda install -c pytorch3d pytorch3d
```

**Comment by kampelmuehler** [comment]
That did the trick, I updated the PR to include the working install instructions.

**Comment by bottler** [comment]
Thanks for fixing this!

**Pull request closed without merging**
